name: cafeteria
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  google_fonts: 6.3.2
  flutter_masked_text2: ^0.9.0
  english_words: ^4.0.0
  provider: ^6.0.7
  intl: ^0.20.2
  qr_flutter: ^4.0.0
  http: any
  mask_text_input_formatter: ^2.5.0
  cached_network_image: ^3.2.3
  http_parser: ^4.0.2
  flutter_localizations:
    sdk: flutter
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/pngtree-coffee-logo-design-png-image_6352424.png"
  adaptive_icon_background: "#FFFFFF"  # Cor de fundo branca
  adaptive_icon_foreground: "assets/images/pngtree-coffee-logo-design-png-image_6352424.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/




